CREATE TABLE 'command' (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`cmdString`	TEXT NOT NULL UNIQUE,
	`isPositive`	INTEGER DEFAULT 0
);
CREATE TABLE `relation` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`intent`	TEXT NOT NULL,
	`command`	INTEGER NOT NULL
);
CREATE TABLE 'histroy'	(
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`command`	TEXT NOT NULL,
	`time`	TEXT NOT NULL
);
